services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  microserviceeshopproject.catalogapi:
    image: ${DOCKER_REGISTRY-}microserviceeshopprojectcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/MicroserviceEShopProject.CatalogAPI/Dockerfile

  microserviceeshopproject.basketapi:
    image: ${DOCKER_REGISTRY-}microserviceeshopprojectbasketapi
    build:
      context: .
      dockerfile: Services/Basket/MicroserviceEShopProject.BasketAPI/Dockerfile

  microserviceeshopproject.discount.grpc:
    image: ${DOCKER_REGISTRY-}microserviceeshopprojectdiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/MicroserviceEShopProject.Discount.Grpc/Dockerfile

  microserviceeshopproject.orderingapi:
    image: ${DOCKER_REGISTRY-}microserviceeshopprojectorderingapi
    build:
      context: .
      dockerfile: Services/Ordering/MicroserviceEShopProject.OrderingApi/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:




