services:
  catalogdb:
    image: postgres

  microserviceeshopproject.catalogapi:
    image: ${DOCKER_REGISTRY-}microserviceeshopprojectcatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/MicroserviceEShopProject.CatalogAPI/Dockerfile

volumes:
  postgres_catalog:

